### ISSUE TITLE
it doesnt work??

### ISSUE THREAD

**Issue by italianjesus** [thejoabo/virtualfisher-bot#1]
i installed the required things and when i type python release.py, nothing shows up.

**Comment by thejoabo** [comment]
Yes, it does. But you have to set some things up first.

When you start the program for the first time, the script creates a .config file (and it should automatically open for you) if it doesn't, **check the folder for a .config file**. There you should put some basic information (here is a template of what it should look like: [template](https://github.com/thejoabo/virtualfisher-bot/blob/main/autofish.config) ).

If you don't know how to get the values of the necessary information (such as your token and channel id) [open a new issue](https://github.com/thejoabo/virtualfisher-bot/issues/new) so that I can guide you step by step.

Why is the information needed?

They are essential for the bot to understand which user should be "listened to" and which channel should be marked for that. No information is shared or even sent anywhere.
