### ISSUE TITLE
My screen is too small, and when editing it returns an error.

### ISSUE THREAD

**Issue by SpaceDevz** [thejoabo/virtualfisher-bot#15]
So my screen is a little too small Whatver x 31 instead of Whatever x 37, so I tried to change it but it just outputs:

[E] Something went wrong -> addwstr() returned ERR

Any way to fix?

**Comment by thejoabo** [comment]
Hello @SpaceDevz,
So, I "hard coded" those values (112, 37) so all the information needed should fit without any problems on the terminal. The "addwstr()" raises an error when the string size if too big or x and y axis is set to a value outside the screen. When you changed those values, you basically are allowing the information to be displayed outside the screen that is why you always getting this error. The way to fix it is by reverting your modification (back to 37 - the default height). 

**I can release a compact mode, where the information is limited to only the really important ones. This would fit your needs, since shouldn't be a problem to smaller screens. Would this work for you ?**

**Comment by SpaceDevz** [comment]
Yes, sorry for the trouble in making a new release. I wish I could just get a bigger monitor but thanks for the help!

**Comment by thejoabo** [comment]
No problem at all. I'll close this issue for now and mention you when I commit the update containing the compact mode.

**Comment by thejoabo** [comment]
Hey @SpaceDevz , I just finished the compact mode. Also, i opened a discussion here #23 , what do you think about the design ? The minimum size is small enough for your needs ? Do you have any suggestions ? (If possible, answer there, please) =)
