### ISSUE TITLE
Unsanitized emoji

### ISSUE THREAD

**Issue by yudhistiraindyka** [thejoabo/virtualfisher-bot#20]
Hello @thejoabo, I just found out that the duplicator (unlocked on level 500) perk's emoji is unsanitized. I tried to play around with the regex but still can't seem to find out why it happens.
![image](https://user-images.githubusercontent.com/33085123/181436662-204fae8f-1d82-4b71-94f4-14a5acae5540.png)
![image](https://user-images.githubusercontent.com/33085123/181436678-45eda42e-53eb-471c-a0fc-83183af45430.png)

**Comment by thejoabo** [comment]
Hello @yudhistiraindyka , I thought that only those custom emotes appear in this type of embed so I made the regex like this: `sub(r'<.+?>', '', line)` so it would perfectly handle this emote patter: _<:fb_fishraw:624818450090557460>_. To fix it is pretty simple, by adding a new regex ( `sub(r':.+?: ', '', content)` ) along with the other one.

Thanks for reporting it. I will fix it in the next update (it's taking more time than I expected to finish it, since I'm changing a lot of things).
