### ISSUE TITLE
AutoFishBot Crashing

### ISSUE THREAD

**Issue by DarkStarsGaming** [thejoabo/virtualfisher-bot#21]
Hello, while I am using the autofish bot I keep crashing.

C:\Users\PcName\Downloads\virtualfisher-bot-main\virtualfisher-bot-main>python autofishbot.py

[*] Starting...
[*] Session stablished !
[E] Something went wrong -> addwstr() returned ERR

I am getting this error and it ends up just crashing it.

**Comment by yudhistiraindyka** [comment]
Hello @DarkStarsGaming, the latest release should run a check on your console window size so you can resize it to make sure the program can run properly. I believe @thejoabo is planning to release a compact version of the program later down the line so in the meantime, I'll provide you an alternative.
I would suggest running the console in full screen mode or setting your window size by doing this:
1. Right click on the console window 
2. Click properties 
3. Set the window size to minimum 112x37 pixel, though I personally set it like this
![image](https://user-images.githubusercontent.com/33085123/181572526-c8111a3c-acd2-4ecc-bf44-c93da32dc6b9.png)

If you want to retain the default window size for the next time you launch it, right click on your console window but instead of clicking properties, click defaults, and set it to the same number as before. Hope it helps!

**Comment by thejoabo** [comment]
#15

**Comment by DarkStarsGaming** [comment]
Hello,

This didn't really help me with my issue not gonna lie all it did was change the size.

I keep on getting the same error:
[] Starting...
[] Session stablished !
[E] Something went wrong -> addwstr() returned ERR
![image](https://user-images.githubusercontent.com/59534560/181616269-9f8f80d9-67d9-4645-b9d8-dc8a898911d5.png)

**Comment by thejoabo** [comment]
@DarkStarsGaming can you try to maximize your terminal and see if it works ?

**Comment by DarkStarsGaming** [comment]
No, I am not seeing that message while I am using it maybe a few min after re-supplying then it just crashes, I am not sure if it's because I need to have the tab open or not.

I will keep you updated if it stops crashing after full-screening

**Comment by thejoabo** [comment]
@DarkStarsGaming Ok, if you want, try to set the "**DEBUG**" constant to **True** in the "_autofishbot.py_" source code it should be right here: 
![image](https://user-images.githubusercontent.com/49594896/181634545-925b4db0-38a6-4986-8244-184f70567db3.png)
It might show some information about whats going on after it crashes. In the new version that I'm currently working on, I added some few more safety checks around the strings size and placement of messages. I will close this issue as "not planned" for now, after I push the update I shall mention you here. 

Feel free to re-open this issue in case of the debug show anything related to the crash.
