### ISSUE TITLE
Stuck at creating new config

### ISSUE THREAD

**Issue by archilles89** [thejoabo/virtualfisher-bot#25]
https://imgur.com/a/Z65VLX5

Hello, I tried installing but it always get stuck right after creating new config.

**Comment by thejoabo** [comment]
Hello @archilles89 , You can manually create this config manually by copying the "[_template.config_](https://github.com/thejoabo/virtualfisher-bot/blob/main/assets/template.config)" file from the **assets** folder to you **config** folder and changing the values as specified by the template and [FAQ](https://github.com/thejoabo/virtualfisher-bot/blob/main/assets/faq.md). The problem seems to be the ConfigParser package, I'll try to investigate whats going on.
