### ISSUE TITLE
Compact Mode Socket Closed

### ISSUE THREAD

**Issue by SpaceDevz** [thejoabo/virtualfisher-bot#26]
`[E] Connection lost -> socket is already closed. Probable cause: incorrect token. ` is the error i get when I try to launch, I have tried getting a new token still doesnt work.

**Comment by thejoabo** [comment]
Hello @SpaceDevz , **this error occurs only on compact mode ?** Also, there is no much I can do about this exception, the description is "_WebSocketConnectionClosedException -> If remote host closed the connection or some network error happened, this exception will be raised._". This means that either your request is being blocked by Discord's API (like ip ban, dns issue) or there is some internal problem on your network.

Try enabling debug on your config and run again to see if any logs show up, and check if you removed the quotation marks on the token. Anyways, there is no way I can reproduce your error on my environment since it depends exclusively on the remote host. 

**Since when this problem start to happen ?**

**Comment by SpaceDevz** [comment]
Hey!

Figured it out I had quotes around my token, because it said str above so I assumed u needed quotes. Do i need quotes aroudn the bait too?

**Comment by thejoabo** [comment]
No, for each parameter, just paste the value there (as plain text, no quotes). But this misunderstanding is my fault, I should sanitize the token value before connecting to the webgate. I'll correct this on the next update.
Thanks for reporting.
