### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by Bluefate1010** [thejoabo/virtualfisher-bot#28]
Not an issue but would be helpful if you can provide a stepwise installation guide or link to any if there is one alredy, i dont really know about all these coding stuff so please try to help

**Comment by thejoabo** [comment]
Hello @Bluefate1010 , 
1) **Install** python : https://www.python.org/ftp/python/3.10.6/python-3.10.6-amd64.exe
2) If you have [Git](https://github.com/git-for-windows/git/releases/download/v2.37.2.windows.2/Git-2.37.2.2-64-bit.exe) on your machine, just **follow the steps from [Installation and usage](https://github.com/thejoabo/virtualfisher-bot#installation-and-update)** from readme, otherwise:
2.1) **Download** the bot zip file: https://github.com/thejoabo/virtualfisher-bot/archive/refs/heads/main.zip
2.2) **Extract** the zip (using [WinRar](https://www.win-rar.com/postdownload.html?&L=0))
2.3) **Open a terminal** (cmd) on the extracted folder and **type** "_pip install -r requirements.txt_" 
2.4) On the extracted folder, using the terminal, **type:** "_python autofishbot.py_" and wait for the prompt to set a config name.
3) It should automatically open this new config on your text editor, then **configure** it properly by following [this example](https://github.com/thejoabo/virtualfisher-bot/blob/main/assets/template.config), for more help related to the config: [FAQ](https://github.com/thejoabo/virtualfisher-bot/blob/main/assets/faq.md). After that, save the file.
4) Finally, **run the bot** using "_python autofishbot.py_" on the extracted folder.

If something is not clear or you run into some error, feel free to ask again =)

**Comment by Bluefate1010** [comment]
Hi, I downloaded the file and extracted it and i used python cmd and cmd prompt both and typed pip install -r requirements.txt but it dosent do anything. It keeps on saying error sorry mate for the trouble

**Comment by RanggaGibran** [comment]
Hello @Bluefate1010 , That's because the path where pip.exe is, is not in your system PATH variable so cmd can't find pip a simple fix will be to change to the directory where pip.exe and run if from there like this

cd C:\Python27\Scripts
But a better solution is to add it to your PATH variable. Open Command prompt with admin rights and run

setx path "%PATH%;C:\Python27\Scripts;"
that adds python to your PATH, you can check the lists of paths in your path variable by running

echo %path%

or u can try with " py -m pip "

**Comment by Bluefate1010** [comment]
> Hello @Bluefate1010 , That's because the path where pip.exe is, is not in your system PATH variable so cmd can't find pip a simple fix will be to change to the directory where pip.exe and run if from there like this
> 
> cd C:\Python27\Scripts But a better solution is to add it to your PATH variable. Open Command prompt with admin rights and run
> 
> setx path "%PATH%;C:\Python27\Scripts;" that adds python to your PATH, you can check the lists of paths in your path variable by running
> 
> echo %path%
> 
> or u can try with " py -m pip "

Yeah that dosent work or i dont get it so i installed git and ran git clone https://github.com/thejoabo/virtualfisher-bot.git
cd virtualfisher-bot
pip install -r requirements.txt and got 
$ ~git clone https://github.com/thejoabo/virtualfisher-bot.git
cd virtualfisher-bot
pip install -r requirements.txt
bash: ~git: command not found
bash: cd: virtualfisher-bot: No such file or directory
bash: pip: command not found

**Comment by thejoabo** [comment]
Hey @Bluefate1010 ,
So, "_git clone_" will just download the repository folder, if you downloaded the zip and extracted it, you can ignore this step. "_cd_" goes to an directory and since the folder wasn't created, obviously failed. Also, instead of "_pip_" try "_python -m pip install -r requirements.txt_" to see if works.

I recorded this on a VM, it might help you: https://www.youtube.com/watch?v=MaaA6V5LBQw 
As you can see on the video, if I had my console opened prior any installation it won't recognize the command (maybe thats why yours isn't working ?)

**Comment by thejoabo** [comment]
@Bluefate1010, No, you need to fill in the information on the notepad itself (if you need help finding the info, check [FAQ](https://github.com/thejoabo/virtualfisher-bot/blob/main/assets/faq.md)), then save it. After that, run the bot again (using "_python autofishbot.py_"), it will start fishing.

**Comment by Bluefate1010** [comment]
Ok now it runs btw what is 
![image](https://user-images.githubusercontent.com/77564709/185275620-fd63cc91-8924-41d7-bd78-9570f14c8445.png)

**Comment by thejoabo** [comment]
This timer is based on the "BUFF_LENGTH" parameter, but since you set the "AUTO_BUFF" off, it will just sell all fishes and buy some baits (so you won't run out of it).

(and i just realized the typo lol, *resupply)

I'll be closing this issue, feel free to make a new one in case something else go wrong.

**Comment by Bluefate1010** [comment]
Oh okay, Great piece of work it really is great...
Its working now and i love it and i really want to thank you and Gibran for helping me out
