### ISSUE TITLE
Would love to have a beta on the image captcha

### ISSUE THREAD

**Issue by SpaceDevz** [thejoabo/virtualfisher-bot#5]
Title, if it is possible.

**Comment by thejoabo** [comment]
Hello @SpaceDevz ,

I'm working on a complete rewrite (since the last one was quite bad and a lot of small things changed). For now, related to captcha, I'm trying to increase the OCR precision and making some more tests on how much (and if) the _"%verify regen"_ command influences the ban rates (since sometimes more then one image is needed to bypass it). Furthermore, I need to fix some UI issues. **I'll commit as soon as I'm done.**

**Comment by SpaceDevz** [comment]
Ok, thanks! I will just type in the captcha manually for now.
