### ISSUE TITLE
Stops working

### ISSUE THREAD

**Issue by werbna** [thejoabo/virtualfisher-bot#6]
so it runs the command to buy %buy leeches -6 which ends up just stopping the bot completely.

**Comment by thejoabo** [comment]
Hello @werbna ,

   The "%buy" command usage syntax is: _%buy \<item\> \<amount\>_  where  _amount is > 0_. If it is a negative number it will stop working ([example](https://prnt.sc/_d_8yd4x6uI9)). 

   When I made the re-buy function (so you won't run out of baits during the fishing session) I did a simple equation to figure out a **probable** (since there is a chance of you don't consume the item upon casting) ideal amount to resupply and not exceed that much the usage rate: `(( boostColldown * 60) / userColldown) * 0.55` (where the boost cd is either 5 or 20 (minutes) and the user cd is delay between you can fish again ([this one](https://prnt.sc/zTrwr8JAS0w8)) and the "0.55" is a arbitrary constant that represent your chance to not consume the item).

   Therefore, for your amount to be "-6" something is very wrong with those two parameters in your config file (_autofish.config_):
- _"cooldown"_
- _"boostcd"_

If possible, **reply with a screenshot or a text paste including your config file parameter**s. Keep in mind that a new update is coming and i rewrote a lot of these small issues. I'll commit as soon as I'm done.

**NOTE: REMEMBER TO ERASE YOUR 'token' VALUE BEFORE SENDING IT.**

**Comment by werbna** [comment]
bait = leeches
buffswitch = true
cooldown = 3200
boostcd = 5
logmode = n
logcaptcha = false
autofish_on_exit = false

**Comment by thejoabo** [comment]
I'm pretty sure your problem is those "3200" seconds in the 'cooldown' parameter. This delay should be in seconds, try changing it to "3.2" and tell me if it works.

**Comment by werbna** [comment]
thank you @thejoabo much appreciated.
